pipeline {
    agent any

    stages {
        
        stage('Environment Setup') {
            steps {
                // Inicjalizacja środowiska (np. instalacja zależności)
                sh 'python -m pip install --upgrade pip'
                sh 'pip install pytest' 
            }
        }
        
      

        stage('Run Tests') {
            steps {
                // Uruchomienie testów jednostkowych
                sh 'python -m unittest discover -s .'
            }
        }

        stage('Deploy') {
            steps {
                // Wywołanie funkcji deploy
                sh 'echo "Jestem w sekcji deploymentu"'
            }
        }
    }
}
